### ISSUE TITLE
Permissions error while running mas-cli-generate-config-secrets init container

### ISSUE THREAD

**Issue by 11qu1d** [small-hack/matrix-authentication-service-chart#50]
Hi,

First of all, great work with all these charts. They are great!

Reporting an issue i encountered while deploying MAS using the umbrella chart.

While running the `mas-cli-generate-config-secrets` init container i get this error:

```
2024-10-27T13:00:27.849402Z  INFO cli.config.generate:generate: mas_config::sections::secrets: Generating keys...
2024-10-27T13:00:27.939886Z  INFO cli.config.generate:generate:rsa: mas_config::sections::secrets: Done generating RSA key
2024-10-27T13:00:27.940152Z  INFO cli.config.generate:generate:ec_p256: mas_config::sections::secrets: Done generating EC P-256 key
2024-10-27T13:00:27.940415Z  INFO cli.config.generate:generate:ec_p384: mas_config::sections::secrets: Done generating EC P-256 key
2024-10-27T13:00:27.941084Z  INFO cli.config.generate:generate:ec_k256: mas_config::sections::secrets: Done generating EC secp256k1 key
2024-10-27T13:00:27.941356Z  INFO cli.config.generate: mas_cli::commands::config: Writing configuration to "/data/config-secrets.yaml"
Error: Permission denied (os error 13)
```

Not sure how this works, but maybe the `/data` directory needs different permissions? Also, noticed that the image used is still using the old archived repo.

Thanks!

**Comment by jessebot** [comment]
Thanks for reporting this! I'm gonna update the image now! Can you post your values.yaml (after anonymizing anything sensitive) so I can take a look at what the problem might be? :)

**Comment by 11qu1d** [comment]
Thanks for looking into this, here are the values im passing via the umbrella chart:

```yaml
mas:
  enabled: true
  postgresql:
    enabled: false
  externalDatabase:
    enabled: true
    existingSecret: matrix-cluster-mas-app
    secretKeys:
      databaseHostname: host
      database: dbname
      databaseUsername: username
      userPasswordKey: password
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: mas.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mas-tls
        hosts:
          - mas.example.com
  networkPolicies:
    enabled: false
  configVolume:
    storageClass: ceph-block-ssd
  mas:
    http:
      public_base: https://mas.example.com
      listeners:
        - name: web
          resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
            - name: assets
          binds:
            - host: 0.0.0.0
              port: 8080
    clients:
      - client_id: "0000000000000000000SYNAPSE"
        client_auth_method: client_secret_basic
        client_secret: "supersecret"
    matrix:
      homeserver: matrix.example.com
      endpoint: https://matrix.example.com
      secret: "supersecret"
    passwords:
      enabled: true
    upstream_oauth2:
      providers:
        - id: someid
          issuer: "https://auth.example.com/application/o/matrix/"
          human_name: Authentik
          client_id: "authentikclientid"
          client_secret: "supersecret"
          scope: "openid profile email"
          token_endpoint_auth_method: client_secret_basic
          claims_imports:
            subject:
              template: "{{ user.sub }}"
            localpart:
              action: require
              template: "{{ user.preferred_username }}"
            displayname:
              action: suggest
              template: "{{ user.name }}"
            email:
              action: suggest
              template: "{{ user.email }}"
              set_email_verification: always
```

**Comment by 11qu1d** [comment]
Just for people stumbling into the original issue, there is a simple fix. Not ideal, but if you add this to the pod config you won't get the permissions error:

```yaml
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
```

@jessebot thanks for updating the container, when you have a minute can you also please update the main matrix chart?
